### PR TITLE
fix(deps): update dependencies

### LINKED ISSUE #334: Audit warning when installing decktape `3.4.0`
Puppeteer needs to be updated to get rid of an audit warning

```
node_modules/decktape/node_modules/ws
  puppeteer-core  11.0.0 - 22.11.1
  Depends on vulnerable versions of ws
  node_modules/decktape/node_modules/puppeteer-core
    decktape  >=3.4.1
    Depends on vulnerable versions of puppeteer
    Depends on vulnerable versions of puppeteer-core
    node_modules/decktape
    puppeteer  18.2.0 - 22.11.1
    Depends on vulnerable versions of puppeteer-core
    node_modules/decktape/node_modules/puppeteer

4 high severity vulnerabilities
```

### PR DESCRIPTION
**Pull request by nicojs**
Update all dependencies. This will remove the audit warnings when installing decktape.

Closes #334

### CODE REVIEW

**Comment by nicojs** [comment]
Commit 8f7fe3b85babd47606503e9dc3a4242692945c7a also includes an actual bugfix. It ensures that puppeteer waits for all web fonts to be loaded on the slide. 

I've included this, because the [build was failing with a wrong screenshot match](https://github.com/astefanutti/decktape/actions/runs/9592461806/job/26451061974). I'll separate it out into a separate PR.

I don't know why the docker build "buildx" is failing. 😢

**Comment by astefanutti** [comment]
> I don't know why the docker build "buildx" is failing. 😢

That's the chromium package that needs to be updated:

```
3.467 ERROR: unable to select packages:
3.474   chromium-126.0.6478.61-r0:
3.475     breaks: world[chromium=122.0.6261.94-r0]
```

I can take care of it before cutting the next release.

**Comment by astefanutti** [comment]
@nicojs do you want to remove commit 3281d79d8c783f3adc65d4c9d08209bf959b94c1 and continue the discussion in #337?

**Comment by nicojs** [comment]
Done. Feel free to Squash merge :)

**Comment by astefanutti** [comment]
Thanks a ton!

**Comment by nicojs** [comment]
Can we create a new release?

**Comment by astefanutti** [comment]
Yes, I plan to do it in the next days.

**Pull request merged**
