### PR TITLE
convert README to AsciiDoc

### PR DESCRIPTION
**Pull request by mojavelinux**
The result looks almost identical to the Markdown version, with the exception of some minor revisions I made to the writing and layout.

### CODE REVIEW

**Comment by astefanutti** [comment]
Awesome, thanks!

Out of curiosity, is there a way to divide the content of a list across multiple columns directly in Asciidoc, somehow using the `column-count` CSS property in HTML backends?

**Comment by mojavelinux** [comment]
:+1: 

To answer your question, yes, but not on GitHub. AsciiDoc supports an "inline" style over any list that will arrange the list horizontally.

```
[inline]
* one
* two
* three
```

However, GitHub strips away all CSS, so there's nothing we can do to control the layout of a list on GitHub.

One workaround is to use a table to split the list into multiple columns, using AsciiDoc-style table cells to host the list.

Another approach is to list them horizontally using a data separator:

```
Bespoke.js | CSSS | deck.js | ...
```

That might work best in this case.

Sidebar: This use case has got me thinking that we should integrate flexbox for different layouts in the default Asciidoctor stylesheet.

**Comment by astefanutti** [comment]
I'd like something like:
```
Bespoke.js         DZSlides              impress.js          Shower
CSSS               Flowtime.js           remark
deck.js            HTML Slidy            reveal.js
```
I think that'd avoid loosing all that screen estate and improve the readability.

With the table approach, I guess there would be no way of hiding the table structure on Github?

Remains the horizontal list then.

That's unfortunate. Thanks anyway.

**Comment by mojavelinux** [comment]
> [I'd like to] avoid loosing all that screen estate and improve the readability.

Would you like me to send a PR?

> That's unfortunate.

That's life on GitHub sometimes :/

**Pull request merged**
