### PR TITLE
Add support for NueDeck

### PR DESCRIPTION
**Pull request by twitwi**
This plugin is for NueDeck (a reboot of deck.js (and many extensions), using Vue.js, https://github.com/twitwi/nuedeck )

I don't know what is the policy for including new plugins into the main repo:
- NueDeck is currently very new, is this blocking?
- should I update the decktape readme for the PR?
- also, is there a way for a plugin to change the default "pause"?

Thanks for working on decktape.

### CODE REVIEW

**Comment by astefanutti** [comment]
Thanks a lot for the PR.

> I don't know what is the policy for including new plugins into the main repo:
>  * NueDeck is currently very new, is this blocking?

Not at all.

> * should I update the decktape readme for the PR?

Yes, I think you can update the list of supported plugins and the CLI help output.

> * also, is there a way for a plugin to change the default "pause"?

Currently no. I was thinking we could add an optional API, as it could help speeding up the export for some plugins a lot. Could you create an issue to track that enhancement?

**Comment by twitwi** [comment]
Thanks, I opened https://github.com/astefanutti/decktape/issues/189

**Comment by twitwi** [comment]
Readme updated! (with some pain)

**Comment by astefanutti** [comment]
Thanks, sorry for the poor man grid layout :)

Would you mind updating the CLI help by adding `nuedeck` to the possible values for the `command`?

**Comment by twitwi** [comment]
no problem,
done

**Comment by astefanutti** [comment]
Thanks!

**Pull request merged**
