### PR TITLE
Add slimerjs support

### PR DESCRIPTION
**Pull request by hadim**
PhantomJS backend works as before.

SlimerJS can generate png files to a temp dir. But I didn't find a way to merge them to generate a pdf file.

Any help would be appreciated :-D

PS: don't worry for unordered and weird commit messages, I'll rebase later.

### CODE REVIEW

**Comment by hadim** [comment]
Any idea on this ?

**Comment by astefanutti** [comment]
@hadim apologizes for the delay, As commented in #6, I'll review and integrate it ASAP.

**Comment by hadim** [comment]
Don't merge it yet !

SlimerJS support does not work really well for now. It only renders slides one by one as png file. I am stuck at merging these files to produce a final pdf file containing all the slides.

I tried several strategies but none of them worked. Since I am very new to JS programming you may found the solution.

- jsPDF and pdfkit does not work: I tried many way to include them without success...
- I also try to call an external process such as `convert tmp_dir/*.png slides.pdf` but `child_process` is not yet supported in SlimerJS (https://github.com/laurentj/slimerjs/issues/215). Anyway it's not the right way to do it since it requires an external dependencies (ImageMagick) and won't work under windows I guess...

We also need a way for a plateform independant temporary directory to store the .png files.

If you have ideas I will be happy to try them.

SlimerJS would be really great as backend since QtWebKit does not support well my slides...

**Comment by astefanutti** [comment]
I don't have a straight solution in mind. I need to experiment on this to find a proper / acceptable solution.

I definitely agree that this is a must-have. This is my next major TODO item :)

**Comment by astefanutti** [comment]
I've just tested PDF rendering that's available in SlimerJS 0.10.0 and that works great. Obviously, it faces the limitation of writing one PDF file per page / slide. Still, in the meantime I figure a way to replicate the new API I create in PhantomJS for SlimerJS (https://github.com/astefanutti/phantomjs/commit/093ca2f41415150236a1abd796228f550ddc058f), that looks like a better approach, given that we find a way to merge the individual PDFs into a single document.

**Comment by hadim** [comment]
Very nice !

I am afk for some weeks but i'll test that when I'll be back.

Printer you created for PhantomJS would be really usefull in SlimerJS.
Le 17 juil. 2015 8:25 AM, "Antonin Stefanutti" <notifications@github.com> a
écrit :

**Comment by hadim** [comment]
Ae you still interested by this @astefanutti ? I will finish the PR.

I want the slimerjs backend to be disabled when `--screenshots=false` since pdf rendering don't work nicely for now and I still don't know how to merge multiple png to a single pdf.

slimerjs backend will work when `--screenshots=true`

Next it would be nice to merge it and we can open new PR to make future improvments (merge pdf, etc).

Hope it's fine to you !

**Comment by hadim** [comment]
I just rebased to `master` and modified the PR.

It works nicely for me. See for example the following command : 

```sh
/path/to/slimerjs /path/to/decktape.js http://lab.hakim.se/reveal-js/#/
                                       --pause 2000
                                       --screenshots
                                       --screenshots-directory ./temp_pdf/
convert ./temp_pdf/*.png slides.pdf
rm -fr ./temp_pdf/
```

When running with `slimerjs` and without `--screenshots` option, Decktape exit with this message `Please use --screenshots and --screenshots-directory option when using SlimerJS backend.`.

If you are ok with this backend system. I think you can merge it and then we can open new PR in the future.

**Comment by hadim** [comment]
There is trick to run SlimerJS on Docker. See https://github.com/nim23/docker-slimerjs/blob/master/Dockerfile

I will investigate more once you have reviewed and merged this PR.

**Comment by astefanutti** [comment]
@hadim yes, I'm definitely interested in adding SlimerJS support for DeckTape.

I would not disable PDF export though, but just output multiple PDF files that the user could merge with an external tool. The SlimerJS backend implementation could just take the `filename` argument and adds a incremented suffix to it.

That'd help progressing towards having the same level of functionality across backends. In that perspective, my idea is to add a default PhantomJS backend as well (as opposed to the forked / improved version of PhantomJS).

**Comment by hadim** [comment]
I didn't see I closed the issue...

Hum the thing is pdf rendering using SlimerJS does not work well for me... Can you try from your side ?

**Comment by astefanutti** [comment]
I'll try ASAP. From what I remember, results vary depending on the presentation framework. SlimerJS PDF export relies on Firefox / Gecko printing functionality which is pretty much like clicking the print button and messes up the layout depending on the framework implementation.

Still, I think that any backend should be capable of providing perfect viewport vectorial export (like PDF) so that I'd rather let the PDF export available despite the poor fidelity output. Obviously, we'd warn the end-user appropriately.

**Comment by hadim** [comment]
Ok I agree. Let me push a commit and then I let you review the whole thing.

**Comment by hadim** [comment]
Last commit has not been tested cuz I need to go.

**Comment by hadim** [comment]
Did you have time to check the PR ?

**Comment by astefanutti** [comment]
@hadim I'll review it ASAP and get back to you.

**Comment by astefanutti** [comment]
Migration to [Puppeteer](https://github.com/GoogleChrome/puppeteer) is underway, see #100. So let's close that PR.

**Pull request closed without merging**
