### PR TITLE
test(harness): Add e2e testing harness using playwright

### LINKED ISSUE #253: Add some e2e tests
Hi, it's me again 🙋‍♂️

How would you feel about adding some e2e tests using screenshot snapshots? This is my idea:

- [ ] Add a testing harness with input directories where we run decktape on.
- [ ] Add playwright as a dependency and open the pdfs in a browser using [the workaround suggested by the playwright team](https://github.com/microsoft/playwright/issues/19253#issuecomment-1338955863)
- [ ] Open each page in the generated pdf and match the snapshots to the snapshot on the disk
- [ ] Add a CI pipeline where we run these snapshot tests
- [ ] Add a manual pipeline that can automatically update the snapshots, which you can efficiently run on a branch of your choice.

I use this approach in a couple of repositories, and it works great IMO. It would save you a lot of time as a maintainer and (hopefully) prevent regression.

### PR DESCRIPTION
**Pull request by nicojs**
Add a e2e testing harness using playwright. Also add 1 demo scenario using the [revealjs demo presentation](revealjs.com/demo/)

To add more e2e tests, add more scenarios to the `test/input` directory. New scenarios found there are automatically picked up.

- Add a simple webserver implementation to serve presentations and pdf files using [koa](https://koajs.com/), a small modern web server.
- Add a `test-prepare-pdfs` script to generate pdfs based on the scenarios in the `test/input` directory.
- Add a `test` script to open the pdfs with playwright using a [known workaround](https://github.com/microsoft/playwright/issues/19253#issuecomment-1338955863)
    - Verify each page in each pdf using snapshot tests
- Add a `ci` workflow that runs for each PR and commit, as well as scheduled each week.
- Add a `update-snapshots` workflow that can be triggered manually. It needs a `GH_TOKEN` secret, which you [can generate via the github UI](https://github.com/settings/tokens?type=beta)

Closes #253

### CODE REVIEW

**Comment by nicojs** [comment]
I see that the demo has a lot of external images. Maybe it's better to pull them into the `input/revealjs-demo` directory? What do you think @astefanutti ?

**Comment by nicojs** [comment]
It turned out to be not a lot of files, so I went ahead and did it.

**Review by astefanutti — APPROVED** [review]
Thanks a lot, this is awesome! One question, do you think it'll make sense (not necessary now), that the source of truth be a PDF instead of a set of images, and the same approach that's used to load the output PDF with pdf.js is reused to load the input PDF, so the two are compared that way? It seems having the source of truth to be PDFs would be more manageable.

**Comment by nicojs** [comment]
That's actually a great idea, I wasn't thinking about that. It would mean a manual "update-snapshot" process, which I can automate for you in the update-snapshots workflow.

**Comment by astefanutti** [comment]
> That's actually a great idea, I wasn't thinking about that. It would mean a manual "update-snapshot" process, which I can automate for you in the update-snapshots workflow.

That manual "update-snapshot" would be perfectly ok. Would you rather prefer to have that PR merged as is, or keep it open until we move to using PDFs as the source of truth? I'm fine either ways 👍🏼.

**Comment by astefanutti** [comment]
Let's merge this. We can look into using PDFs as the source of truth later. Thanks again!

**Pull request merged**
