### PR TITLE
plugin to print from Jupyter notebooks with RISE plugin installed

### PR DESCRIPTION
**Pull request by anaderi**

### CODE REVIEW

**Comment by astefanutti** [comment]
Thanks. I've amended the RISE plugin to use the Reveal.js API as much as possible.

**Comment by anaderi** [comment]
Great! while I was writing it, Reveal object wasn't available inside `evaluate` function for some reason. That's why I've used 'generic' approach. Did you apply any magic?

**Comment by astefanutti** [comment]
@anaderi I faced that issue too. DeckTape's plugin `configure` API supports a `Promise` instance as return type so I've used that capability to delay the Reveal.js configuration a bit after _clicking_ on the RISE button, see: https://github.com/astefanutti/decktape/blob/4d68a0afa45253a023d34554b56546339299ba4c/plugins/rise.js#L17-L38.

**Comment by anaderi** [comment]
ah, magic indeed )
BTW, 2000 ms delay shouldn't be a plugin parameter (line 36)?

**Comment by astefanutti** [comment]
I don't think that's necessary to add a parameter for that. I've tried 1000 ms and it was failing from time to time. It looks like 2000 ms is longer enough.

**Comment by akaihola** [comment]
@astefanutti, I actually had to add another delay before clicking the `#start_livereveal` button. Otherwise I always got the "Reveal object not available" error.

**Comment by astefanutti** [comment]
@akaihola did you try with the latest version of the plugin? I've added a delay before clicking the `#start_livereveal` a while ago as I faced the same issue, see:
https://github.com/astefanutti/decktape/blob/244e4ab95c31035032e3e1b18bd990a057107560/plugins/rise.js#L22

**Comment by akaihola** [comment]
@astefanutti, I was using the 1.0.0 release. I'll try with a development checkout from GitHub next time.

**Pull request merged**
