### PR TITLE
List frameworks as inline list in README

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by astefanutti** [comment]
@mojavelinux I've just tried using the table approach to list the supported frameworks in multiple columns. Apparently, Github isn't taking the `width`, `.<`, nor the `grid` attributes into account.

I'm still wondering what's the best compromise, though would you know whether these attributes are supported by Github or not?

**Comment by mojavelinux** [comment]
Your observation is correct. The best way to think of it is that GitHub strips everything out except the HTML tags themselves (with exceptions only where the attribute is part of the content, like the src attribute on img). GitHub does this to all markup languages, not just AsciiDoc. They are generally unwilling to have a conversation about it. Life on GitHub.

The best way to display them horizontally is just to put them in a single paragraph with some sort of spacer.

**Comment by mojavelinux** [comment]
I think the proposal I sent looks reasonable.

**Comment by astefanutti** [comment]
Would there be a way somehow with AsciiDoc to produce anchors within a source block as the `<a>` element is supported within a `<pre>` element?

I've tried:
```
[source,subs="macros,attributes"]
----
link:{uri-bespokejs}[Bespoke.js]
----
```
But it doesn't work :(

**Comment by mojavelinux** [comment]
Yep.

```
[subs="attributes+,+macros"]
....
{uri-bespokejs}[Bespoke.js]
....
```

Technically, the incremental subs order doesn't matter on GitHub, but this would be the proper way to enable links in source code that is being highlighted, so it's just a good practice to write it this way.

(Btw, you should always use incremental subs on a source block unless you intend to include the specialchars substitution. Without the specialchars substitution, it will treat the content as raw HTML).

**Comment by mojavelinux** [comment]
The `+` is the position of the verbatim substitution.

**Comment by astefanutti** [comment]
Great, I've just tried it and that works. So we have:
* https://github.com/mojavelinux/decktape/blob/inline-framework-list/README.adoc
* https://github.com/astefanutti/decktape/blob/test/README.adoc

Which one would you think be preferable?

**Comment by mojavelinux** [comment]
Cool! I like either one. The verbatim block does make the source look a bit weird in order to accomplish a better presentation, but if that's a trade-off you're comfortable with, then I'd say go with it.

**Comment by astefanutti** [comment]
Cool. I'll go for the hacky way then until there is a better way to do multi-column lists on GitHub. As you said, that's life on GitHub :grin:.

For some reasons, the hacky code block does not render in Atom AsciiDoc preview...

Anyway, thanks a lot for all your inputs! Always a pleasure to collaborate with you!

**Comment by mojavelinux** [comment]
The preview doesn't work in Atom because the Atom plugin is still using Asciidoctor 1.5.2 (which is older than it sounds). The Atom plugin really needs to get upgraded. The Chrome extension shows a preview of what is achievable with Atom.

> Always a pleasure to collaborate with you!

Same here!

**Pull request closed without merging**
